name: 'Fetch Github Release Assets'
description: 'Downloads multiple assets from a Github release'

inputs:
  repo:
    description: 'org/repo to download from'
    required: false
    default: ''
  version:
    description: 'Version of the release to download from'
    required: false
    default: 'latest'
  file:
    description: 'Pattern of the files in the release to download (regex)'
    required: true
  token:
    description: 'Optional Personal Access Token to access external repository'
    required: false
    default: ''
  path:
    description: 'Output path for the downloaded files'
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.version }}
    - ${{ inputs.file }}
    - ${{ inputs.token }}
    - ${{ inputs.path }}

outputs:
  version:
    description: 'The version of the release or tag'

branding:
  icon: 'download-cloud'
  color: 'orange'
